### PR TITLE
TWW2.8.0.2 Beta

### PR DESCRIPTION
**Pull request by prastle**
Latest Update

### CODE REVIEW

**Comment by prastle** [comment]
I believe this is ready now @ron-murhammer  @ssoloff  @DanVanAtta

**Review by ssoloff — APPROVED** [review]
Started a new game from this branch and played a few rounds on the BETA map without any problems.

Because I'm not really familiar with this map, I'm going to leave it open for @DanVanAtta and @ron-murhammer, in case they have any concerns.  I'll return if it's not merged in a day or two.

**Comment by DanVanAtta** [comment]
Looks okay to me, but I'm not familiar with this map. We're okay to release a new version, too? This seems like it would not be compatible (good to move forward, the gfx look nice)

**Comment by prastle** [comment]
ron already looked at it and the fixes have been made.  Yes it includes the old and new map.  He is afk now I just noticed you were online.  All good. we can wait

**Pull request merged**
